# Generated by Django 4.2.1 on 2023-06-11 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = ()

    operations = ()
