version: '3.4'

services:
  web:
    image: petstagram
    build: .
    # ./Dockerfile
    # context: .
    command: gunicorn --bind=0.0.0.0:8000 petstagram.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - ./envs/.env
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: petstagram_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
      - /tmp/app-resources/static:/app/static
  nginx:
    image: nginx
    ports:
      - '81:80'
      - '443:443'
    volumes:
      - /tmp/django_deploy/static:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - web